name: CI TEST
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      - run: go version

    - name: Checkout code
      - uses: actions/checkout@v2
    - name: Test
      run: go test -v -cover ./...